### ISSUE TITLE
Javascript Runtime ?

### ISSUE THREAD

**Issue by yaf** [simplonco/simplonline#8]
``` bash
➜  sensei git:(master) ✗ rake -T
rake aborted!
ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/sstephenson/execjs for a list of available runtimes.
/home/yaf/Code/sensei/.bundle/gems/execjs-2.2.0/lib/execjs/runtimes.rb:51:in `autodetect'
/home/yaf/Code/sensei/.bundle/gems/execjs-2.2.0/lib/execjs.rb:5:in `<module:ExecJS>'
/home/yaf/Code/sensei/.bundle/gems/execjs-2.2.0/lib/execjs.rb:4:in `<top (required)>'
/home/yaf/Code/sensei/.bundle/gems/uglifier-2.5.1/lib/uglifier.rb:3:in `require'
/home/yaf/Code/sensei/.bundle/gems/uglifier-2.5.1/lib/uglifier.rb:3:in `<top (required)>'
/home/yaf/Code/sensei/config/application.rb:8:in `<top (required)>'
/home/yaf/Code/sensei/Rakefile:4:in `require'
/home/yaf/Code/sensei/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```

From a fresh install...

**Comment by yaf** [comment]
Fix with https://github.com/simplonco/sensei/commit/f9f5074e81f05dec87bf7d96136bd15ccc893f13
